[package]
name = "infra"
version = "0.1.0"
edition = "2021"


[dependencies]
ai = { path = "../ai" }
persistence = { path = "../libs/persistence" }
anyhow.workspace = true
tokio.workspace = true
tracing.workspace = true
uuid.workspace = true
