[build]
target = "index.html"
dist = "dist"
public_url = "/"

[serve]
port = 8080

[[hooks]]
stage = "pre_build"
command = "mkdir"
command_arguments = ["-p", "dist"]

[[hooks]]
stage = "build"
command = "cp"
command_arguments = ["-r", "public/.", "dist/"]
